default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.1.3
    hooks:
      - id: clang-format
        args: [--style=LLVM]
      - id: clang-tidy
        args: [--checks=.clang-tidy]
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
      - id: cmakelint
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
